### ISSUE TITLE
Finder toolbar icon

### ISSUE THREAD

**Issue by fabian** [pketh/open-in-chocolat#1]
Great app, thanks!

But somehow the icon doesn't really fit with all other buttons in my toolbar?

![Screenshot](http://f.cl.ly/items/0R2K2Q213D2y3F3X2a04/Screen%20Shot%202015-03-05%20at%2010.58.56.png)

Is there a hidden option in Finder to have smaller toolbar buttons?

```
OS X Yosemite
Version 10.10.2
```

**Comment by pketh** [comment]
Hi, glad you like it :)

This is an issue I have as well that I can't figure out a workaround for. Apple's own internal toolbar icons are generated dynamically from black/white png pdfs in the system folder. I suspect dropbox is extending the finder in some way. However this technique isn't publicly documented anywhere :(

custom icons dragged in will always be smaller - this is the case in both Mavericks and Yosemite.

What I do is place my custom icons together and seperate from the native ones so that this doesn't bother me as much:

![screen shot 2015-03-05 at 8 08 04 pm](https://cloud.githubusercontent.com/assets/877072/6518362/5f6f99a2-c373-11e4-8389-9f39aa7fc010.png)

**Comment by fabian** [comment]
I see, thanks for the explanation! Will keep the icon on the right side as well. ;-)

**Comment by pketh** [comment]
no problem :+1:
